version: '3.7'

services:
  web:
    image: nginx
    deploy:
      replicas: 5
      endpoint_mode: vip
      placement:
        constraints:
          - node.role == worker
      resources:
        reservations:
          cpus: '0.1'
          memory: 50M
    ports:
      - "8000:80"
    networks:
      - minha_rede
    deploy:
      resources:
        reservations:
          cpus: '0.1'
          memory: 50M
    environment:
      - SWARM_MODE=1
    configs:
      - source: my_config
        target: /app/config.txt
      - source: my_secret
        target: /app/secret.txt

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8888:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - minha_rede
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  minha_rede:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24

configs:
  my_config:
    file: ./config.txt
  my_secret:
    file: ./secret.txt

volumes:
  jenkins_home:
